# Generated by Django 2.2.1 on 2019-06-19 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicleentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnumber', models.CharField(max_length=10)),
                ('vtype', models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=10)),
                ('contactno', models.CharField(default='', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('intime', models.DateTimeField(auto_now_add=True)),
                ('spacealloted', models.CharField(max_length=10)),
                ('flooralloted', models.CharField(max_length=10)),
                ('tagno', models.CharField(max_length=10)),
            ],
        ),
    ]
