# Generated by Django 2.2.1 on 2019-06-19 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20190619_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='intime',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 14, 14, 30, 823322)),
        ),
    ]
