# Generated by Django 2.2.1 on 2019-06-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20190619_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='intime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
