# Generated by Django 2.2.1 on 2019-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_auto_20190620_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='intime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
