# Generated by Django 2.2.1 on 2019-06-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_auto_20190622_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleexit',
            name='tno',
        ),
        migrations.RemoveField(
            model_name='vehicleexit',
            name='vno',
        ),
        migrations.RemoveField(
            model_name='vehicleexit',
            name='vtypee',
        ),
        migrations.AddField(
            model_name='vehicleexit',
            name='fare',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
