# Generated by Django 2.2.1 on 2019-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_auto_20190623_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleexit',
            name='tdiff',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleexit',
            name='tno',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleexit',
            name='vno',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicleexit',
            name='vty',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], default='two', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleexit',
            name='farem',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
