# Generated by Django 2.2.1 on 2019-06-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_auto_20190624_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleexit',
            name='tdiff',
        ),
    ]
